#!/usr/bin/env python3
"""Turn a Figma wallpaper export into the plate the SVG background samples.

The export is ~11.8 MB, and almost none of that is vector: it is one
3344x1882 PNG base64'd into a <defs>, plus a backdrop blur and a grain filter.
Inlining it verbatim would put ~8.9 MB gzipped on every page.

So the export is split along the line of what each half is good at:

  * the blur is static, so it is baked here, once, at build time. Blur leaves
    nothing above a fairly low spatial frequency, which is why the plate
    survives being stored at a third of its width: even at the low end of the
    range this script is used at, storing at 878 rather than native 2632 costs
    a maximum of 2/255 on any pixel. What ships is ~23 KB instead of 8.5 MB.

  * the grain stays in the SVG as a live feTurbulence, because that is the part
    that would suffer from being baked. Resampled grain moires, and JPEG spends
    a fortune encoding it. As a filter it is resolution independent, costs no
    bytes, and dithers the banding an 8-bit blurred gradient would show.

Geometry is read out of the export rather than transcribed, and written to
site/content/wallpaper.mjs, so the markup cannot drift from the plate.

    python3 scripts/build_wallpaper.py path/to/002.svg
"""

from __future__ import annotations

import argparse
import base64
import io
import re
from pathlib import Path

from PIL import Image, ImageFilter


ROOT = Path(__file__).resolve().parents[1]
PLATE = ROOT / "public" / "page" / "desktop" / "wallpaper.jpg"
GEOMETRY = ROOT / "site" / "content" / "wallpaper.mjs"

# Stored width. Well above what the blur can carry, so there is room to soften
# the blur later without regenerating anything upstream.
STORE_W = 878

# How much the plate is blurred, in source-image pixels. The export's own
# backdrop-filter measures 26 here, solved against Chrome's render rather than
# read off the file, because the two do not agree: it asks for blur(28px) in
# viewBox units and 26 in source pixels is what actually matches.
#
# This sits well below that on purpose. At 26 the logomark in each bell is
# mush; by 10 it reads; at 7 the filaments inside the bell come back while the
# glow still stays soft enough not to compete with the windows on top of it.
# Raise it toward 26 to go back to what Figma exported.
BLUR = 7

EMBEDDED = re.compile(rb'href="data:image/(?:png|jpeg);base64,([^"]+)"')
PLATE_RECT = re.compile(
    r'<rect x="(-?[\d.]+)"(?: y="(-?[\d.]+)")? width="([\d.]+)" height="([\d.]+)" fill="url\(#pattern'
)
BASE_RECT = re.compile(r'<rect width="([\d.]+)" height="([\d.]+)" fill="(#[0-9A-Fa-f]{6})"\s*/>')


def read_export(svg: Path):
    """Pull the raster, the plate's placement and the base colour out of the export."""
    raw = svg.read_bytes()
    embedded = EMBEDDED.search(raw)
    if not embedded:
        raise SystemExit(f"{svg} has no embedded raster; is it a Figma export?")
    image = Image.open(io.BytesIO(base64.b64decode(embedded.group(1)))).convert("RGB")

    text = raw.decode("utf8", "replace")
    base = BASE_RECT.search(text)
    rect = PLATE_RECT.search(text)
    if not base or not rect:
        raise SystemExit(f"{svg} does not have the shape this script expects")

    view = (round(float(base.group(1))), round(float(base.group(2))))
    placement = (
        round(float(rect.group(1))),
        round(float(rect.group(2) or 0)),
        round(float(rect.group(3))),
        round(float(rect.group(4))),
    )
    return image, view, placement, base.group(3)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("svg", type=Path, help="the Figma SVG export")
    parser.add_argument("--blur", type=float, default=BLUR)
    arguments = parser.parse_args()

    source, view, (x, y, width, height), colour = read_export(arguments.svg)

    plate = source.resize((width, height), Image.LANCZOS)
    plate = plate.filter(ImageFilter.GaussianBlur(arguments.blur))
    plate = plate.resize((STORE_W, round(STORE_W * height / width)), Image.LANCZOS)

    PLATE.parent.mkdir(parents=True, exist_ok=True)
    plate.save(PLATE, format="JPEG", quality=82, optimize=True, progressive=True)

    GEOMETRY.write_text(
        f'''// Generated by scripts/build_wallpaper.py from {arguments.svg.name}. Do not edit:
// these numbers have to agree with the plate, and the script writes both.
export const WALLPAPER = {{
  view: {{ width: {view[0]}, height: {view[1]} }},
  plate: {{ x: {x}, y: {y}, width: {width}, height: {height} }},
  colour: "{colour}",
  source: "/page/desktop/wallpaper.jpg",
}};
'''
    )

    print(f"  source      {source.size[0]}x{source.size[1]}")
    print(f"  view        {view[0]}x{view[1]}, base {colour}")
    print(f"  plate       {width}x{height} at ({x}, {y}), stored {plate.size[0]}x{plate.size[1]}")
    print(f"  blur        {arguments.blur:g}  (the export itself measures 26)")
    print(f"  wrote       {PLATE.relative_to(ROOT)}, {PLATE.stat().st_size / 1024:.1f} KB")
    print(f"  wrote       {GEOMETRY.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
